spring.application.name=UAMBite

server.port=8090
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://192.168.1.23:8927/uambite
spring.datasource.username=uambite_admin
spring.datasource.password=kP9x.mQ2!vW5*zT8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true